# Configurations
title: Minerva
tagline: The owl of Minerva flies at dusk
description: 在黄昏起飞的猫头鹰,可以看见整个白天所发生的一切,可以追寻其他鸟儿在白天自由翱翔的足迹。- Hegel

author:
  name: cloudhan
  url: https://symphonyh.github.io/
  email: hxy@cloudhan.me

plugins:
  - jekyll-paginate

paginate: 5


categories_path: /categories/
tags_path: /tags/

disqus:
  shortname: symphonyh-github-io

url: http://symphonyh.github.io/
